/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbooksIdRouteImport } from './routes/ebooks.$id'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedEbookIndexRouteImport } from './routes/_authenticated/ebook.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedWorkoutIdRouteImport } from './routes/_authenticated/workout.$id'
import { Route as AuthenticatedEbookIdRouteImport } from './routes/_authenticated/ebook.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminMigrationRouteImport } from './routes/_authenticated/admin/migration'
import { Route as AuthenticatedAdminEbooksRouteImport } from './routes/_authenticated/admin/ebooks'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as ApiPublicWebhooksCaktoRouteImport } from './routes/api/public/webhooks/cakto'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksIdRoute = EbooksIdRouteImport.update({
  id: '/ebooks/$id',
  path: '/ebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbookIndexRoute = AuthenticatedEbookIndexRouteImport.update({
  id: '/ebook/',
  path: '/ebook/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedWorkoutIdRoute = AuthenticatedWorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbookIdRoute = AuthenticatedEbookIdRouteImport.update({
  id: '/ebook/$id',
  path: '/ebook/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMigrationRoute =
  AuthenticatedAdminMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEbooksRoute =
  AuthenticatedAdminEbooksRouteImport.update({
    id: '/ebooks',
    path: '/ebooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksCaktoRoute = ApiPublicWebhooksCaktoRouteImport.update({
  id: '/api/public/webhooks/cakto',
  path: '/api/public/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/ebooks/$id': typeof EbooksIdRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ebook/$id': typeof AuthenticatedEbookIdRoute
  '/workout/$id': typeof AuthenticatedWorkoutIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/ebook/': typeof AuthenticatedEbookIndexRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/ebooks/$id': typeof EbooksIdRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ebook/$id': typeof AuthenticatedEbookIdRoute
  '/workout/$id': typeof AuthenticatedWorkoutIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ebook': typeof AuthenticatedEbookIndexRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
  '/ebooks/$id': typeof EbooksIdRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/_authenticated/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/ebook/$id': typeof AuthenticatedEbookIdRoute
  '/_authenticated/workout/$id': typeof AuthenticatedWorkoutIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/ebook/': typeof AuthenticatedEbookIndexRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planos'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workouts'
    | '/ebooks/$id'
    | '/admin/billing'
    | '/admin/ebooks'
    | '/admin/migration'
    | '/admin/plans'
    | '/admin/users'
    | '/ebook/$id'
    | '/workout/$id'
    | '/admin/'
    | '/ebook/'
    | '/api/public/webhooks/cakto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planos'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workouts'
    | '/ebooks/$id'
    | '/admin/billing'
    | '/admin/ebooks'
    | '/admin/migration'
    | '/admin/plans'
    | '/admin/users'
    | '/ebook/$id'
    | '/workout/$id'
    | '/admin'
    | '/ebook'
    | '/api/public/webhooks/cakto'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/planos'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/workouts'
    | '/ebooks/$id'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/ebooks'
    | '/_authenticated/admin/migration'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/users'
    | '/_authenticated/ebook/$id'
    | '/_authenticated/workout/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/ebook/'
    | '/api/public/webhooks/cakto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EbooksIdRoute: typeof EbooksIdRoute
  ApiPublicWebhooksCaktoRoute: typeof ApiPublicWebhooksCaktoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$id': {
      id: '/ebooks/$id'
      path: '/ebooks/$id'
      fullPath: '/ebooks/$id'
      preLoaderRoute: typeof EbooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebook/': {
      id: '/_authenticated/ebook/'
      path: '/ebook'
      fullPath: '/ebook/'
      preLoaderRoute: typeof AuthenticatedEbookIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/workout/$id': {
      id: '/_authenticated/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof AuthenticatedWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebook/$id': {
      id: '/_authenticated/ebook/$id'
      path: '/ebook/$id'
      fullPath: '/ebook/$id'
      preLoaderRoute: typeof AuthenticatedEbookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/migration': {
      id: '/_authenticated/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AuthenticatedAdminMigrationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ebooks': {
      id: '/_authenticated/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AuthenticatedAdminEbooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/cakto': {
      id: '/api/public/webhooks/cakto'
      path: '/api/public/webhooks/cakto'
      fullPath: '/api/public/webhooks/cakto'
      preLoaderRoute: typeof ApiPublicWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminEbooksRoute: typeof AuthenticatedAdminEbooksRoute
  AuthenticatedAdminMigrationRoute: typeof AuthenticatedAdminMigrationRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
    AuthenticatedAdminEbooksRoute: AuthenticatedAdminEbooksRoute,
    AuthenticatedAdminMigrationRoute: AuthenticatedAdminMigrationRoute,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
  AuthenticatedEbookIdRoute: typeof AuthenticatedEbookIdRoute
  AuthenticatedWorkoutIdRoute: typeof AuthenticatedWorkoutIdRoute
  AuthenticatedEbookIndexRoute: typeof AuthenticatedEbookIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
  AuthenticatedEbookIdRoute: AuthenticatedEbookIdRoute,
  AuthenticatedWorkoutIdRoute: AuthenticatedWorkoutIdRoute,
  AuthenticatedEbookIndexRoute: AuthenticatedEbookIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EbooksIdRoute: EbooksIdRoute,
  ApiPublicWebhooksCaktoRoute: ApiPublicWebhooksCaktoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
